Feature/social login
wecode-bootcamp-korea/49-3rd-OneMore-backend pull request #11
Opened 2023-10-18 12:27 UTC by xxoung32

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  :  회원가입과 로그인을 좀 더 간편하게 하기 위해서

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
 
: 회원 가입과 로그인 절차를 간소화하여 좀 더 쉽게 가입과 로그인을 할 수 있다.
 

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

<카카오 소셜 로그인 구현>

- passport 라이브러리를 사용하여 카카오 소셜 로그인을 구현하였다.

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 

<br />

![스크린샷 2023-10-18 21-23-28](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/142733059/0f1c980e-1c55-4c46-aeb7-8aa25d6933b3)
 
추가)
![스크린샷 2023-10-18 21-24-13](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/142733059/ae179f95-6d96-46f7-bf95-99d6114c4999)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 소셜로그인 로직에 대해 공부하게 되었다
- passport라는 라이브러리에 대해 알게 되었다
  <br />

2023-10-19 05:02 UTC, JISUlicious requested changes

2023-10-19 05:02 UTC, JISUlicious commented on src/controllers/userController.js
> +// const userService = require("../services/userService");
MongoNetworkError는 사용되는건가요?
사용되지 않는 것 같은데 확인하고 삭제 부탁드려요

2번째 줄 주석처리된 것도 필요하지 않으니 삭제~

2023-10-19 05:02 UTC, JISUlicious commented on src/middleware/passport.js
> +  }
코드 들여쓰기 한번 맞춰주세요~

2023-10-19 05:02 UTC, JISUlicious commented on app.js
> +// }))
사용 하지 않는 코드/주석 삭제하면 좋겠습니다~

2023-10-19 05:02 UTC, JISUlicious commented on .env.sample
> +KAKAO_CALLBACK_URL="CALLBACK"
env sample 예시가 적절하지 않아보입니다, 수정하면 좋겠습니다~

2023-10-19 05:49 UTC, JISUlicious approved these changes

2023-10-20 11:44 UTC, soheon-lee requested changes
전반적인 로직은 크게 달라질 것이 없고, 몇개 코멘트 확인 후 답변 주시면 머지 하겠습니다 :)

2023-10-20 11:44 UTC, soheon-lee commented on src/controllers/userController.js
> +
불필요한 공백은 제거해 주세요~

2023-10-20 11:44 UTC, soheon-lee commented on src/middleware/passport.js
> +    console.log("kakaoprofile: ", profile)
개발이 끝났다면 콘솔로그 제거해 주세요 :)

2023-10-20 11:44 UTC, soheon-lee commented on src/middleware/passport.js
> +      console.log("exisitingUserBySocial: ", exisitingUserBySocial)
개발이 끝났다면 콘솔로그 제거해 주세요 :)

아래 다른 코드에서도 마찬가지 입니다

2023-10-20 11:44 UTC, soheon-lee commented on src/models/userDao.js
> +};
```suggestion
const findUserBySocial = async (socialUid, socialProvider) => {
  const [foundUserBySocial] = await AppDataSource.query(
    `SELECT id
     FROM users
     WHERE social_account_uid = ? AND social_account_provider = ?`,
    [socialUid, socialProvider])
  return foundUserBySocial;
};
```

2023-10-20 11:44 UTC, soheon-lee commented on src/models/userDao.js
> +
- 이건 어떤 상황에서 정보 수정하시는걸까요?
- 수정할 때는 users의 id가 이미 잇기 때문에 email이 아닌 userId를 가지고 정보를 수정하셔야 합니다

2023-10-20 11:44 UTC, soheon-lee commented on src/routes/userRouter.js
> +//users/oauth/kakao
주석 제거해 주세요

2023-10-21 04:19 UTC, xxoung32 commented on src/controllers/userController.js
> +
공백 제거 완료했습니다

2023-10-21 04:21 UTC, xxoung32 commented on src/middleware/passport.js
> +    console.log("kakaoprofile: ", profile)
콘솔 제거 완료했습니다

2023-10-21 04:23 UTC, xxoung32 commented on src/middleware/passport.js
> +      console.log("exisitingUserBySocial: ", exisitingUserBySocial)
넵 제거 완료 했습니다!

2023-10-21 04:29 UTC, xxoung32 commented on src/models/userDao.js
> +};
수정 완료 했습니다!

2023-10-21 04:36 UTC, xxoung32 commented on src/models/userDao.js
> +
- 유저가 직접 서비스에 이메일로 회원가입한 후, 같은 이메일로 소셜 로그인을 할 때, 해당 유저의 계정을 소셜 계정으로 수정하는 로직입니다.
- email => userId로 변경 완료했습니다.

2023-10-21 04:37 UTC, xxoung32 commented on src/routes/userRouter.js
> +//users/oauth/kakao
넵! 주석 제거 완료 했습니다

2023-10-23 04:30 UTC, soheon-lee approved these changes
어려운 기능 수고하셨습니다 아영님-!

2023-10-23 04:32 UTC, merged