Feature/routine end
wecode-bootcamp-korea/49-3rd-OneMore-backend pull request #12
Opened 2023-10-19 13:46 UTC by Park-KJ

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?
 : 고객이 진행 완료 한 루틴에 대해 상태를 변경하고, 이후 고객이 루틴에 재진입시 상태정보를 보여주는 기능 필요

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?
 : 루틴 내 운동들에 대해 상태정보 변경이 가능(완료한 운동도 다시 완료 취소하여 운동 재시작 가능)

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

운동 완료 기능 추가
 - 오늘의 루틴(추천 루틴)에 포함된 운동 중 완료 체크 된 운동에 대해 운동 완료로 상태 변경 및 메시지 전송
 - routineDao.js  :  updateCompletedExerciseStatusbyRoutineId, checkExerciseIdsInRoutine 에 대한 내용

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
![image](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/132734576/5ad869cb-ff7e-4920-b199-53fc232b0861)

![image](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/132734576/e2be47c0-249b-4dff-a84e-7f354ee49d0f)

![image](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/132734576/2b41f368-edb9-41ee-8d36-b1a8657b6b00)

![image](https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/132734576/f28b06a9-6fab-4757-913b-15ac94306e12)

## 4. 이 브랜치에서 개발하면서 느꼈던 개발 성장포인트를 적어주세요.
 : 코드 작성의 컨벤션에 대한 부분을 조금 더 알게 됨
 : 세심한 확인 필요  :  확인을 위한 console.log 삭제  /  체크를 위한 함수(쿼리문)에서 모든 데이터(*)를 줄 필요가 없다. 등

2023-10-19 14:51 UTC, soheon-lee commented
PR 템플릿 1번 사항 작성해 주세요~

<img width="896" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/42701133/ec659942-6691-479d-8b87-e2a85f77d819">

2023-10-19 15:00 UTC, soheon-lee requested changes
Test code.... 작성하시느라 정말 수고 하셨습니다. 👏 👏

2023-10-19 15:00 UTC, soheon-lee commented on src/controllers/routineController.js
> +    console.log("req.body:::::::::", req.body);
개발용 console.log는 모두 지우셔야 합니다.........

2023-10-19 15:00 UTC, soheon-lee commented on src/models/routineDao.js
> +};
```suggestion
//  →  기존에 완료한 운동도 체크 해제하면 미완료로 변경 가능하게

const exerciseStatus = {
  COMPLETED : 1
  NOT_COMPLETED : 0
}
const updateCompletedExerciseStatusbyRoutineId = async (
  routineId,
  exercisesId
) => {
  await AppDataSource.query(
    `UPDATE routine_exercises
    SET completed = exerciseStatus.COMPLETED
    WHERE routine_id = ? AND exercise_id IN (?)`,
    [routineId, exercisesId]
  );
};
```

1. 그냥 completed = 1 이라고 하면, 1과 0의 상태가 어떠한 경우인지 모든 개발자가 외우고 있거나, 참조가 필요하게 됩니다. 숫자를 값으로 매핑하면, 커뮤니케이션 시간을 줄일 수 있고, human error가 발생할 확률을 줄일 수 있습니다 :)

2. 더 나아가, 보다 확장성 있는 함수를 만들 수 있는 방법은, status (상태) 에 대한 값도 함수의 인자로 받아오게 함수를 선언하고, status를 service layer에서 내려주는 방법이 있습니다.

2023-10-19 15:00 UTC, soheon-lee commented on src/services/routineService.js
> +  const result = routineDao.checkExercisesIdInRoutine(routineId, exercisesId);
```suggestion
  const result = routineDao.checkExerciseIdsInRoutine(routineId, exercisesId);
```

2023-10-19 15:00 UTC, soheon-lee commented on src/services/routineService.js
> +  console.log("exercisesId.length:::::::::", exercisesId.length);
?_?

2023-10-19 15:00 UTC, soheon-lee commented on src/models/routineDao.js
> +    `SELECT *
모든 필드를 다 선택하실건가요?

2023-10-20 06:39 UTC, Park-KJ commented on src/services/routineService.js
> +  const result = routineDao.checkExercisesIdInRoutine(routineId, exercisesId);
service, dao에 같은 이름의 함수가 있는데, 위 함수처럼   dao.함수명   으로 사용해도 괜찮을까요?
그리고 리뷰 달아주신 부분은 단순히 문법상 안맞기때문에 수정이 필요한 건가요?

2023-10-20 07:58 UTC, Park-KJ commented on src/models/routineDao.js
> +    `SELECT *
인자로 받는 값 2개  +  id만 선택하도록 수정 완료
입니다~

2023-10-20 07:59 UTC, Park-KJ commented on src/controllers/routineController.js
> +    console.log("req.body:::::::::", req.body);
삭제 완료 입니다.............

2023-10-20 08:28 UTC, Park-KJ commented on src/models/routineDao.js
> +};
매 요청마다 모든 상태가 변경되도록 수정했습니다.
routine_id에 속하는 exercise_id를 받으면 해당 운동만 1(운동 완료), 나머지는 0(운동 미완료)로 변경됩니다.
 + 말씀해주신 부분도 반영 완료

변경 함수

const updateCompletedExerciseStatusbyRoutineId = async (id, exercisesId) => {
  const exerciseStatus = {
    COMPLETED: 1,
    NOT_COMPLETED: 0,
  };

  await AppDataSource.query(
    `UPDATE routine_exercises
      SET completed = IF(exercise_id IN (?), ${exerciseStatus.COMPLETED}, ${exerciseStatus.NOT_COMPLETED})
    WHERE routine_id = ?`,
    [exercisesId, id]
  );
};

2023-10-20 08:29 UTC, Park-KJ commented on src/services/routineService.js
> +  console.log("exercisesId.length:::::::::", exercisesId.length);
삭제 완료입니다.

2023-10-20 08:50 UTC, Park-KJ commented on src/services/routineService.js
> +  const result = routineDao.checkExercisesIdInRoutine(routineId, exercisesId);
지수님께 여쭤봐서 해결 했습니다.

1. 상관 없다.
 - 함수명이 같아도 하위단(dao)에서 가져온 것을 명확히 해줬기 때문
 - 흐름상 하나의 업무(?)를 처리하는 로직이기 때문

2. exercisesId  →  exerciseIds
 - exercisesId  :  운동들을 통합하는 id  =  id 1개
 - exerciseIds  :  각 운동들의 id  =  각 운동별 id만큼의 개수

으로 이해했는데, 잘못되거나 추가해주실 부분 있으며 말씀 부탁드립니다.

2023-10-23 11:19 UTC, soheon-lee commented on src/services/routineService.js
> +  const result = routineDao.checkExercisesIdInRoutine(routineId, exercisesId);
1. 네! 함수 이름이 같은것은 상관 없습니다 :) 각 레이어에서 보통 동일하게 사용하는 편입니다.
2. 2번도 후자의 의도가 맞습니다! Id 자체를 배열로 여러개 받아올 것이기 때문에 Ids가 보다 적합합니다

2023-10-23 11:21 UTC, soheon-lee approved these changes
LGTM!
conflict 해결해주시고 머지하십시오 :)

2023-10-24 05:15 UTC, merged