feat: db table created
wecode-bootcamp-korea/49-3rd-OneMore-backend pull request #3
Opened 2023-10-13 11:48 UTC by JISUlicious

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

고객의 서비스 정보를 저장하기 위한 DB 구축 필요

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  모든 서비스의 정보가 DB에 안전하게 저장되어 서비스를 원활하게 사용 가능하게 됨

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

DB 테이블 생성

- 30개 테이블의 migration 파일 작성

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<img width="1251" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/52498558/681853d2-ca6d-4224-94c4-5e1558da7cb4">

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- DB 작성의 중요성을 깨닫다..
  <br />

2023-10-13 11:54 UTC, soheon-lee requested changes
컬럼 관련 리뷰 2개 남겼습니다 :) 확인 후 수정 부탁드립니다.

2023-10-13 11:54 UTC, soheon-lee commented on db/migrations/20231013063247_create-user-related-table.sql
> +  `zip_code` integer NOT NULL,
zip_code 문자열로 변경해 주세요

2023-10-13 11:54 UTC, soheon-lee commented on db/migrations/20231013064220_create-routines-table.sql
> +  `setCounts` integer NOT NULL DEFAULT 1,
```suggestion
  `set_counts` integer NOT NULL DEFAULT 1,
```
snake_case로 명명해 주세요

2023-10-13 12:11 UTC, JISUlicious commented on db/migrations/20231013063247_create-user-related-table.sql
> +  `zip_code` integer NOT NULL,
수정했습니다~

2023-10-13 12:11 UTC, JISUlicious commented on db/migrations/20231013064220_create-routines-table.sql
> +  `setCounts` integer NOT NULL DEFAULT 1,
수정했습니다~

2023-10-16 01:44 UTC, soheon-lee approved these changes
수정 사항 확인했습니다!
LGTM!!

2023-10-16 01:44 UTC, merged