feat: createRoutine 기능 작성
wecode-bootcamp-korea/49-3rd-OneMore-backend pull request #8
Opened 2023-10-17 08:50 UTC by JISUlicious

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  고객이 선택한 운동들을 루틴으로 저장하여 실행할 필요가 있습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  운동 목록에서 원하는 운동을 선택 또는 추천받은 운동 목록을 재생시킴으로 해당 운동들을 하나의 루틴으로 묶어 자장 할 수 있습니다. 생성된 루틴은 추후 루틴 실행 페이지에서 불러올 수 있습니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

루틴 생성 기능 추가

- 선택된 운동의 id들을 받아 해당 유저의 루틴으로 저장
- 유저의 subscription 정보를 비교하여 유료 컨텐츠 포함 여부 확인
- routines 테이블과 routine_exercises 테이블에 데이터를 각각 저장
- transaction을 적용하여 데이터의 무결성을 보장

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<img width="1421" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/52498558/a2797c28-03bc-4513-b87b-efc83d8acfe6">

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- transaction을 직접 구현해보고 transaction에 대한 이해가 깊어졌습니다.
  <br />

2023-10-17 08:51 UTC, JISUlicious commented
test code는 validateToken 기능까지 merge 된 이후에 추가하겠습니다.

2023-10-17 12:20 UTC, JISUlicious commented
validateToken middleware 없이도 내부의 service, dao를 테스트 할 수 있는 코드를 작성하여 추가했습니다.

2023-10-18 04:33 UTC, soheon-lee requested changes
<img width="908" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-OneMore-backend/assets/42701133/eea23219-4b2d-4d30-8bf6-a133b0aae733">

지수님 제가 비어있는 DB에서 테스트 했을 때때 몇몇 테스트가 Fail인데 migration이나 기타 정보에 수정이 필요할까요?

2023-10-18 04:33 UTC, soheon-lee commented on src/controllers/routineController.js
> +    const body = req.body;
- subscriptionState는 userId를 활용해서 user 와 엮인 subscription 관련 테이블에서 조회해서 반영하시는 것이 좋을 것 같습니다.
- 프론트엔드에서 잘못된 정보를 저장하고 있을 확률, 잘못된 정보를 전달할 확률이 있기 때문에 이를 대비하기 위함입니다.

2023-10-18 04:33 UTC, soheon-lee commented on src/services/routineService.js
> +  if (exerciseIds.length === 0) throwError(400, "KEY_ERROR");
1. 이 에러 정상 동작 하나요? body에 exercises라는 키가 안들어오면 KEY_ERROR가 나기 전에 이미 undefined의 length에 접근 해야해서 조건문 내부에서 문법에러가 날 텐데, 확인 한 번 부탁드립니다!
2. 키는 들어오는 안에 내용물이 비어 있는 경우라면, EXERCISE_IDS_EMPTY 등의 메세지가 더 적절할 것 같습니다!

2023-10-18 04:42 UTC, JISUlicious commented
> <img alt="image" width="908" src="https://user-images.githubusercontent.com/42701133/276088317-eea23219-4b2d-4d30-8bf6-a133b0aae733.png">
> 지수님 제가 비어있는 DB에서 테스트 했을 때때 몇몇 테스트가 Fail인데 migration이나 기타 정보에 수정이 필요할까요?

함수명 바꾼 부분이 있는데 제가 제대로 확인 못하고 푸시했네요. 수정해서 다시 올리겠습니다~

2023-10-18 04:43 UTC, JISUlicious commented on src/services/routineService.js
> +  if (exerciseIds.length === 0) throwError(400, "KEY_ERROR");
exercise key가 없는거는 생각 못했네요, 수정하겠습니다

2023-10-18 04:43 UTC, JISUlicious commented on src/controllers/routineController.js
> +    const body = req.body;
넵 테이블에서 확인해서 사용하는쪽으로 수정하겠습니다~

2023-10-18 06:18 UTC, soheon-lee approved these changes
LGTM!!

2023-10-18 06:19 UTC, merged